### ISSUE TITLE
Regex needs to be changed to match new gold image naming convention

### ISSUE THREAD

**Issue by chaitanyaenr** [mbruzek/ansible-openstack-setup#7]
The rhel and atomic gold images will be named with a rhel and atomic tags respectively. For example:
2017-11-01-ocp-3.7.0-0.189.0-atomic-gold.qcow2 #For atomic images
2017-11-01-ocp-3.7.0-0.189.0-rhel-gold.qcow2 #For rhel images

**Comment by mbruzek** [comment]
Thanks for opening an issue to track this change. I put the changes in already under my normal maintenance cycle. Please keep me informed of any other changes on the images.
